/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package PR_VENTANAS;

import PR_Usuarios.Usuarios;
import PR_Usuarios.GestionUsuarios;
import javax.swing.JOptionPane;
import PR_RECURSOS.Sonidos;
import javax.swing.ImageIcon;

public class Inicio extends javax.swing.JFrame {
    private GestionUsuarios gestor;
    private Usuarios usuarioActual;
    private boolean usuarioNuevo = false;
    private Sonidos musica = new Sonidos();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setTitle("PR-PICASSO");
        musica.reproducir("PR_RECURSOS/inicio.wav");
        gestor = new GestionUsuarios();
        jbtnInicio.setEnabled(false);
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("PR_RECURSOS/sonic.png")).getImage());
    }
    
    
    
    private void validarUsuario() {
           String nombre = jtxtUser.getText().trim();

           if (nombre.isEmpty()) {
               JOptionPane.showMessageDialog(this, "Ingrese un nombre de usuario.","INICIO",JOptionPane.INFORMATION_MESSAGE);
               return;
           }   

           usuarioActual = gestor.buscarUsuario(nombre);

           if (usuarioActual == null) {
               usuarioActual = new Usuarios(nombre);
               gestor.agregarUsuario(usuarioActual);
               usuarioNuevo = true;
                JOptionPane.showMessageDialog(this,"Usuario nuevo creado correctamente.","INICIO",JOptionPane.INFORMATION_MESSAGE);
            } else {
            usuarioNuevo = false;
            JOptionPane.showMessageDialog(this,"Bienvenido nuevamente, " + usuarioActual.getNombre(),"INICIO",JOptionPane.INFORMATION_MESSAGE);
           }
           jbtnInicio.setEnabled(true);
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jbtnInicio = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnCreditos = new javax.swing.JButton();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/titulo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        getContentPane().add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 130, 30));

        jbtnInicio.setBackground(new java.awt.Color(102, 0, 153));
        jbtnInicio.setText("Jugar");
        jbtnInicio.addActionListener(this::jbtnInicioActionPerformed);
        getContentPane().add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 91, 37));

        jbtnSalir.setBackground(new java.awt.Color(0, 102, 102));
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(this::jbtnSalirActionPerformed);
        getContentPane().add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 91, 37));

        jbtnOK.setBackground(new java.awt.Color(0, 102, 0));
        jbtnOK.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jbtnOK.setText("OK");
        jbtnOK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnOK.addActionListener(this::jbtnOKActionPerformed);
        getContentPane().add(jbtnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 70, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel2.setText("Ingresa tu nombre");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, 30));

        jbtnCreditos.setBackground(new java.awt.Color(102, 0, 51));
        jbtnCreditos.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jbtnCreditos.setText("CREDITOS");
        jbtnCreditos.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 51, 0)));
        jbtnCreditos.addActionListener(this::jbtnCreditosActionPerformed);
        getContentPane().add(jbtnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 30));

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/fondo1.png"))); // NOI18N
        jlblFondo.setToolTipText("");
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        musica.detener();
        M_Niveles menu = new M_Niveles(usuarioActual, gestor, usuarioNuevo);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnInicioActionPerformed

   
    
    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        validarUsuario();
    }//GEN-LAST:event_jbtnOKActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreditosActionPerformed
        JOptionPane.showMessageDialog(this,
        "PR-PICASSO\n\n" +
        "Desarrollado por Aarón Enrique Yarleque Ramos\n" +
        "© 2026\n\n" +
        "Gracias por jugar.",
        "Créditos",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnCreditosActionPerformed
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCreditos;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables
}
