
package PR_VENTANAS;

import PR_Usuarios.Usuarios;
import PR_Usuarios.GestionUsuarios;
import PR_RECURSOS.Sonidos;
import javax.swing.ImageIcon;

public class M_Niveles extends javax.swing.JFrame {
    
    private Usuarios usuarioActual;
    private GestionUsuarios gestor;
    private Sonidos musica = new Sonidos();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(M_Niveles.class.getName());

    public M_Niveles() {
        initComponents();
        
    }
    
    public M_Niveles(Usuarios usuarioActual, GestionUsuarios gestor) {
        initComponents();
        setTitle("PR-PICASSO");
        this.usuarioActual = usuarioActual;
        this.gestor = gestor;
        mostrarProgreso();
        musica.reproducir("PR_RECURSOS/menu.wav");
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("PR_RECURSOS/sonic.png")).getImage());
        
        jbtnNivel1.setForeground(java.awt.Color.WHITE);
        jbtnNivel2.setForeground(java.awt.Color.WHITE);
        jbtnNivel3.setForeground(java.awt.Color.WHITE);
        
        
        
        jlblFeli.setVisible(false);
            if (usuarioActual.getNivel1() == 1 && usuarioActual.getNivel2() == 1 && usuarioActual.getNivel3() == 1){
                jlblFeli.setVisible(true);
                } else {
                jlblFeli.setVisible(false);
                }

        jlblPing.setVisible(false);
            if (usuarioActual.getNivel1() == 1
                && usuarioActual.getNivel2() == 1
                && usuarioActual.getNivel3() == 1) {

            jlblPing.setIcon(
                new ImageIcon(getClass().getResource("/PR_RECURSOS/Penguin.gif"))
            );

            jlblPing.setVisible(true);
        }
    }
    public M_Niveles(Usuarios usuarioActual, GestionUsuarios gestor, boolean usuarioNuevo) {
        this(usuarioActual, gestor);

        if (usuarioNuevo) {
            mostrarHistoria();
        }
    }
    
    private void mostrarHistoria() {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "EL RESCATE DEL PINGÜINO\n\n" +
            "El malvado Rey Mono ha secuestrado a nuestro amigo Pingüino.\n\n" +
            "Para rescatarlo, deberás viajar por los tres mundos legendarios:\n" +
            "TAGROF, SINOOS y CIGRA.\n\n" +
            "Supera todos los desafíos, consigue las 3 medallas sagradas\n" +
            "y enfréntate a tu destino.\n\n" +
            "Solo entonces el Pingüino volverá a ser libre.",
            "Historia",
            javax.swing.JOptionPane.PLAIN_MESSAGE);
    }
    private void mostrarProgreso() {
        int completados = 0;

        if (usuarioActual.getNivel1() == 1) {
            completados++;
        }

        if (usuarioActual.getNivel2() == 1) {
            completados++;
        }

        if (usuarioActual.getNivel3() == 1) {
            completados++;
        }

        jlblProgreso.setText(completados + "/3");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnNivel1 = new javax.swing.JButton();
        jbtnNivel2 = new javax.swing.JButton();
        jbtnNivel3 = new javax.swing.JButton();
        jbtnRegresar = new javax.swing.JButton();
        jlblMeda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblProgreso = new javax.swing.JLabel();
        jlblFeli = new javax.swing.JLabel();
        jlblPing = new javax.swing.JLabel();
        jbtnHistoria = new javax.swing.JButton();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnNivel1.setBackground(new java.awt.Color(102, 0, 102));
        jbtnNivel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jbtnNivel1.setText("SINOOS");
        jbtnNivel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnNivel1.addActionListener(this::jbtnNivel1ActionPerformed);
        getContentPane().add(jbtnNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 50));

        jbtnNivel2.setBackground(new java.awt.Color(102, 0, 0));
        jbtnNivel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jbtnNivel2.setText("TAGROF");
        jbtnNivel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnNivel2.addActionListener(this::jbtnNivel2ActionPerformed);
        getContentPane().add(jbtnNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 90, 50));

        jbtnNivel3.setBackground(new java.awt.Color(0, 102, 102));
        jbtnNivel3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jbtnNivel3.setText("CIGRA");
        jbtnNivel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnNivel3.addActionListener(this::jbtnNivel3ActionPerformed);
        getContentPane().add(jbtnNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 90, 50));

        jbtnRegresar.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jbtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/flecha.png"))); // NOI18N
        jbtnRegresar.setText("Regresar");
        jbtnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnRegresar.addActionListener(this::jbtnRegresarActionPerformed);
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jlblMeda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/medal.png"))); // NOI18N
        getContentPane().add(jlblMeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setText("SELECCIONE EL MUNDO");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, -1));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblProgreso.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jlblProgreso.setText("0/0");
        jPanel2.add(jlblProgreso);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 50, 30));

        jlblFeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/feli.png"))); // NOI18N
        getContentPane().add(jlblFeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 380, 140));

        jlblPing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/Penguin.gif"))); // NOI18N
        getContentPane().add(jlblPing, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 300, 180));

        jbtnHistoria.setBackground(new java.awt.Color(153, 102, 0));
        jbtnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/hisot.png"))); // NOI18N
        jbtnHistoria.addActionListener(this::jbtnHistoriaActionPerformed);
        getContentPane().add(jbtnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 50, 60));

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/fondo2.png"))); // NOI18N
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNivel2ActionPerformed
        musica.detener();
        Nivel2 n2 = new Nivel2(usuarioActual, gestor);
        n2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNivel2ActionPerformed

    private void jbtnNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNivel3ActionPerformed
        musica.detener();
        Nivel3 n3 = new Nivel3(usuarioActual, gestor);
        n3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNivel3ActionPerformed

    private void jbtnNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNivel1ActionPerformed
        musica.detener();
        Nivel1 n1 = new Nivel1(usuarioActual, gestor);
        n1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNivel1ActionPerformed

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        musica.detener();
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    private void jbtnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHistoriaActionPerformed
        mostrarHistoria();
    }//GEN-LAST:event_jbtnHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new M_Niveles().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnHistoria;
    private javax.swing.JButton jbtnNivel1;
    private javax.swing.JButton jbtnNivel2;
    private javax.swing.JButton jbtnNivel3;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JLabel jlblFeli;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JLabel jlblMeda;
    private javax.swing.JLabel jlblPing;
    private javax.swing.JLabel jlblProgreso;
    // End of variables declaration//GEN-END:variables
}
