/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PR_VENTANAS;

import PR_Usuarios.Usuarios;
import PR_Usuarios.GestionUsuarios;
import javax.swing.JOptionPane;
import PR_RECURSOS.Sonidos;
import javax.swing.ImageIcon;

public class Nivel1 extends javax.swing.JFrame implements BaseNVL{
    private Usuarios usuarioActual;
    private GestionUsuarios gestor;
    private int preguntaActual = 0;
    private Sonidos musica = new Sonidos();
    
    private String[] palabras = {"FELIZ","RÁPIDO","BONITO","GRANDE",
                                 "FUERTE","INTELIGENTE","PEQUEÑO","TRISTE"};
    
    private String[] respuestas = {"alegre","veloz","hermoso","enorme",
                                   "robusto","listo","diminuto","afligido"};
    private String[][] opciones = {
        {"JOCOSO", "TRISTE", "ALEGRE"},
        {"VELOZ", "SUAVE", "PEQUEÑO"},
        {"FEO", "HERMOSO", "ALTO"},
        {"ENORME", "PEQUEÑO", "LENTO"},
        {"ROBUSTO", "DÉBIL", "SUAVE"},
        {"LISTO", "TORPE", "LENTO"},
        {"DIMINUTO", "GRANDE", "FUERTE"},
        {"AFLIGIDO", "ALEGRE", "RÁPIDO"}
    };
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nivel1.class.getName());

    public Nivel1() {
        initComponents();
    }

    public Nivel1(Usuarios usuarioActual, GestionUsuarios gestor) {
        initComponents();
        setTitle("PR-PICASSO");
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("PR_RECURSOS/sonic.png")).getImage());
    
        
        jbtnTutorial.setForeground(java.awt.Color.WHITE);
        jbtnAceptar.setForeground(java.awt.Color.WHITE);
        
        this.usuarioActual = usuarioActual;
        this.gestor = gestor;
        mostrarPregunta();
        
        musica.reproducir("PR_RECURSOS/nivel1.wav");
        tutorial();
        
    }
    
    private void tutorial(){
        JOptionPane.showMessageDialog(this,
            "¡BIENVENIDO A SINOOS!\n\n" +
            "SINOOS es el mundo de los sinónimos.\n" +
            "Aquí las palabras cambian de forma, pero conservan su significado.\n\n" +
            "REGLAS DEL MUNDO:\n" +
            "• Lee atentamente la palabra mostrada.\n" +
            "• Observa las opciones disponibles.\n" +
            "• Escribe el sinónimo correcto.\n" +
            "• Cada respuesta correcta te acerca a la medalla del mundo.\n\n" +
            "Completa todas las preguntas para superar el nivel y continuar tu aventura.");
    }
    @Override
    public void mostrarPregunta() {
        jLabel2.setText("Elige el sinonimo de: " + palabras[preguntaActual]);

        jlblAlt1.setText(opciones[preguntaActual][0]);
        jlblAlt2.setText(opciones[preguntaActual][1]);
        jlblAlt3.setText(opciones[preguntaActual][2]);

        jtxtRespuesta.setText("");
        jtxtRespuesta.requestFocus();
    }

    @Override
    public boolean verificarRespuesta() {
        String respuestaUsuario = jtxtRespuesta.getText().trim().toLowerCase();
        String respuestaCorrecta = respuestas[preguntaActual];

        if (respuestaUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe una respuesta.");
            return false;
        }

        return respuestaUsuario.equals(respuestaCorrecta);
    }

    @Override
    public void completarNivel() {
        usuarioActual.setNivel1(1);
        gestor.actualizarUsuario(usuarioActual);
        
        JOptionPane.showMessageDialog(this, "¡Muy bien! Completaste el Mundo 1.");
        musica.detener();
    }
    
    private void regresarMenu() {
    M_Niveles menu = new M_Niveles(usuarioActual, gestor);
    menu.setVisible(true);
    this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtRespuesta = new javax.swing.JTextField();
        jbtnAceptar = new javax.swing.JButton();
        jbtnRegresar = new javax.swing.JButton();
        jbtnTutorial = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlblAlt1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblAlt3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlblAlt2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setText("MUNDO 1 - SINONIMOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel6.setText("Escribe la respuesta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        getContentPane().add(jtxtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 190, 30));

        jbtnAceptar.setBackground(new java.awt.Color(0, 102, 102));
        jbtnAceptar.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jbtnAceptar.setText("ACEPTAR");
        jbtnAceptar.addActionListener(this::jbtnAceptarActionPerformed);
        getContentPane().add(jbtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 30));

        jbtnRegresar.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jbtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/flecha.png"))); // NOI18N
        jbtnRegresar.setText("REGRESAR");
        jbtnRegresar.addActionListener(this::jbtnRegresarActionPerformed);
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jbtnTutorial.setBackground(new java.awt.Color(0, 102, 102));
        jbtnTutorial.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jbtnTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/infos.png"))); // NOI18N
        jbtnTutorial.setText("Info");
        jbtnTutorial.addActionListener(this::jbtnTutorialActionPerformed);
        getContentPane().add(jbtnTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 153)));

        jlblAlt1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jlblAlt1.setText("ALTERNATIVA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlblAlt1)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblAlt1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 153)));

        jlblAlt3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jlblAlt3.setText("ALTERNATIVA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jlblAlt3)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblAlt3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 153)));

        jlblAlt2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jlblAlt2.setText("ALTERNATIVA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlblAlt2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblAlt2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel2.setText("Elige un sinonimo de :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 390, 40));

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PR_RECURSOS/fondo3.png"))); // NOI18N
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        regresarMenu();
        musica.detener();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
            if (verificarRespuesta()) {

        preguntaActual++;

        if (preguntaActual < palabras.length) {
            JOptionPane.showMessageDialog(this, "¡Correcto! Siguiente palabra.");
            mostrarPregunta();
        } else {
            completarNivel();
            regresarMenu();
        }

    } else {
        JOptionPane.showMessageDialog(this, "Respuesta incorrecta.");
    }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTutorialActionPerformed
        tutorial();
    }//GEN-LAST:event_jbtnTutorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Nivel1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JButton jbtnTutorial;
    private javax.swing.JLabel jlblAlt1;
    private javax.swing.JLabel jlblAlt2;
    private javax.swing.JLabel jlblAlt3;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JTextField jtxtRespuesta;
    // End of variables declaration//GEN-END:variables
}
